# Generated by Django 2.2 on 2020-10-17 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='b_day',
        ),
    ]
