# Generated by Django 2.2 on 2020-11-05 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_registration_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('due_date', models.DateField()),
                ('end_date', models.DateField()),
                ('frequency', models.IntegerField()),
                ('logged', models.BooleanField()),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_expense', to='login_registration_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_image', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='money_app.Item')),
            ],
        ),
        migrations.CreateModel(
            name='PayStub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paystub_image', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paystub_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paystub', to='money_app.Item')),
            ],
        ),
    ]
